# Generated by Django 5.2.7 on 2025-11-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('fecha_posted', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.elemento')),
            ],
        ),
    ]
